import Foundation

class SceneService {
    static let shared = SceneService()
    private init() {}

    let freeScenes: [Scene] = [
        Scene(id: "travel_1", name: "Travel Without Travel",
              description: "Ferry crossings and airplane window views from around the world",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
              isPremium: false, isFree: true, category: "Travel Without Travel", isPurchased: false),
        Scene(id: "window_views_1", name: "Window Views",
              description: "Snow, rain and fog glimpsed through cozy window panes",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
              isPremium: false, isFree: true, category: "Window Views", isPurchased: false),
        Scene(id: "summer_dusk_1", name: "Summer Dusk",
              description: "Warm sunsets over mountains, coasts and golden fields",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
              isPremium: false, isFree: true, category: "Summer Dusk", isPurchased: false),
        Scene(id: "spring_blossoms_1", name: "Spring Blossoms",
              description: "Cherry blossom petals drifting in gentle spring breezes",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
              isPremium: false, isFree: true, category: "Spring Blossoms", isPurchased: false),
        Scene(id: "desert_nights_1", name: "Desert Nights",
              description: "Vast desert skies blanketed in stars",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
              isPremium: false, isFree: true, category: "Desert Nights", isPurchased: false),
        Scene(id: "tropical_dusk_1", name: "Tropical Dusk",
              description: "Vivid tropical sunsets over palm-fringed beaches",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
              isPremium: false, isFree: true, category: "Tropical Dusk", isPurchased: false),
        Scene(id: "floating_balloons_1", name: "Floating Balloons",
              description: "Colorful hot air balloons drifting across clear skies",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
              isPremium: false, isFree: true, category: "Floating Balloons", isPurchased: false),
        Scene(id: "aquarium_fish_1", name: "Aquarium Fish",
              description: "Vibrant tropical fish gliding through crystal-clear water",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
              isPremium: false, isFree: true, category: "Aquarium Fish", isPurchased: false),
    ]

    let premiumScenes: [Scene] = [
        Scene(id: "focus_flow_1", name: "Focus & Flow",
              description: "Geometric patterns and abstract visuals to sharpen your focus",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
              isPremium: true, isFree: false, category: "Focus & Flow", isPurchased: false),
        Scene(id: "grounding_1", name: "Grounding & Stability",
              description: "Ancient trees, tranquil lakes and rugged coastlines",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
              isPremium: true, isFree: false, category: "Grounding & Stability", isPurchased: false),
        Scene(id: "anxiety_relief_1", name: "Anxiety Relief",
              description: "Soft lights and gentle abstract visuals to calm the mind",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
              isPremium: true, isFree: false, category: "Anxiety Relief", isPurchased: false),
        Scene(id: "japanese_forest_1", name: "Japanese Forest Paths",
              description: "Serene bamboo groves and peaceful Japanese garden walks",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
              isPremium: true, isFree: false, category: "Japanese Forest Paths", isPurchased: false),
        Scene(id: "autumn_leaves_1", name: "Autumn Leaves",
              description: "Golden forest paths and swaying autumn foliage",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
              isPremium: true, isFree: false, category: "Autumn Leaves", isPurchased: false),
        Scene(id: "first_snow_1", name: "First Snow",
              description: "Quiet snowfall blanketing forests and fields",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
              isPremium: true, isFree: false, category: "First Snow", isPurchased: false),
        Scene(id: "mountain_1", name: "Mountain & Highlands Calm",
              description: "Sweeping alpine vistas, misty peaks and mountain lakes",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
              isPremium: true, isFree: false, category: "Mountain & Highlands Calm", isPurchased: false),
        Scene(id: "ocean_1", name: "Water Worlds",
              description: "Immersive ocean-inspired ambiance",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
              isPremium: true, isFree: false, category: "Water Worlds", isPurchased: false),
        Scene(id: "desert_1", name: "Desert & Dunes Calm",
              description: "Rolling sand dunes and vast desert landscapes at golden hour",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
              isPremium: true, isFree: false, category: "Desert & Dunes Calm", isPurchased: false),
        Scene(id: "night_horizons_1", name: "Night Horizons",
              description: "Moonlit skies and soft night ambience",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
              isPremium: true, isFree: false, category: "Night Horizons", isPurchased: false),
        Scene(id: "candlelight_1", name: "Candlelight & Fire Glow",
              description: "Warm bonfires, crackling logs and glowing lanterns",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
              isPremium: true, isFree: false, category: "Candlelight & Fire Glow", isPurchased: false),
        Scene(id: "nordic_cabins_1", name: "Nordic Cabins",
              description: "Snow-draped cabins in quiet winter forests",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
              isPremium: true, isFree: false, category: "Nordic Cabins", isPurchased: false),
        Scene(id: "counting_sheep_1", name: "Counting Sheep",
              description: "Peaceful grazing ambience for sleep",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
              isPremium: true, isFree: false, category: "Counting Sheep", isPurchased: false),
        Scene(id: "soft_clouds_1", name: "Soft Clouds",
              description: "Gentle and airy atmosphere for winding down",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
              isPremium: true, isFree: false, category: "Soft Clouds", isPurchased: false),
        Scene(id: "royal_library_1", name: "Royal Library Fireplace",
              description: "Quiet, warm library ambience with fireplace tones",
              thumbnailUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
              isPremium: true, isFree: false, category: "Royal Library Fireplace", isPurchased: false),
    ]

    var featuredScenes: [Scene] { Array(freeScenes.prefix(3)) }

    var allScenes: [Scene] { freeScenes + premiumScenes }

    func scenesInHomeOrder() -> [Scene] {
        featuredScenes + freeScenes + premiumScenes
    }
}
